### ISSUE TITLE
♻ Refactor:  ⚡State Propagation Refinement

### ISSUE THREAD

**Issue by PhearZero** [algodex/algodex-react#177]
# ℹ Overview

Refine propagation of state. AssetInfo should use an upstream APIs (Algorand | Algoexplorer) as a data source to reduce dependence on our backend API. This should also include a refactor to Separate Concerns. 

AssetInfo should be the only state that propagates through the components. Every component is responsible for taking the AssetInfo state as a prop and kicking off it's own effects that relate to it's purpose. 

#### For example: 

```
const Chart = ({asset}) => {
  const {data: chartData, isLoading, isError} = useAssetChartQuery({asset}) 

  isLoading && return <div>Loading...</div>
  isError && return <div>Error!</div>
  return <div>{JSON.stringify(chartData)}</div>
}

const MyHoC = ({asset}) =>{
 return <Chart asset={asset}/>
}
```

***React-Query will share the same context for Queries and respond with cached data. This pattern allows for easy reuse across the frontend without increasing request loads on the required services.***

## 🥅 Goals: 
  - [ ] The Algodex API should only send Smart Contract state to the client.
  - [X] The client should fetch AssetInfo.
  - [X] Separation of Concerns(SoC)

# 📝Issues:
- [ ] algodex/algodex-api/issues/83
    - [ ] Use new endpoint for Orderbook
    - [ ] Use new endpoint for Chart/ChartOverlay 
    - [ ] Only call orders.php from onSubmit of `<PlaceOrderForm/>`
- [X] Deprecate /asset_by_id.php in favor of minimal /assets.php route (No AssetInfo)
- [ ] Deprecate /asset_search.php in favor of in-memory client side searching (Reduce /assets.php with Verified Explorer Assets)
- [x] #179 
- [ ] Deprecate /wallet/orders in favor of "notes" field
