### ISSUE TITLE
♻ Refactor: Styled Components

### ISSUE THREAD

**Issue by PhearZero** [algodex/algodex-react#246]
# ℹ Overview

First pass at refactoring of components. Move useful CSS/tailwinds code to a reusable project called [@algodex/components](https://github.com/algodex/algodex-components). This shouldn't include any major component refactors, just reduce the current surface area of components.

- [x] Find duplicate CSS and create reusable components.
- [x] Remove all *.css.js
- [x] Fill in storied for main components
   - [x] #249
   - [x] #250
   - [x] #253
   - [x] #256
   - [x] #257
   - [x] #260
   - [x] #265
   - [x] ✅ Acceptance: Wallet Connect Component
   - [x] #266
   
### 📝 Related Issues

- [x] #178 
- [ ] algodex/algodex-components#1
