### ISSUE TITLE
♻️ Refactor: Update Typography to Design System 

### ISSUE THREAD

**Issue by PhearZero** [algodex/algodex-react#508]
# ℹ Overview

Update MUI default typography variants and include any custom variants such as `<Typography variant="price" />`

- [X] ✨ Add Price Variant
- [x] ✨ Add H1 Variant
- [x] ✨ Add H2 Variant
- [x] ✨ Add H3 Variant
- [x] ✨ Add H4 Variant
- [x] ✨ Add H5 Variant
- [x] ✨ Add H6 Variant
- [x] ✨ Add subtitle1 Variant
- [x] ✨ Add subtitle2 Variant
- [x] ✨ Add body1 Variant
- [x] ✨ Add body2 Variant
- [x] ✨ Add button Variant
- [x] ✨ Add caption Variant
- [x] ✨ Add overline Variant

### 🔧 Example Typography:

```jsx
const theme = {
  typography: {
    ...muiTheme.typography,
    price: {
      fontFamily: fontFamilies.monospace,
      fontWeight: 400,
      [muiTheme.breakpoints.up('xs')]: {
        fontSize: '0.1rem'
      },
      [muiTheme.breakpoints.up('md')]: {
        fontSize: '0.625rem'
      },
      lineHeight: '1rem',
      letterSpacing: '0.04em',
      textTransform: 'uppercase'
    }
  },
  //... the rest of the theme
}
```
